
CREATE DATABASE QL_NHANSU;
CREATE DATABASE QL_NHANSUQUANCAPHE;

USE QL_NHANSU;
USE QL_NHANSUQUANCAPHE;


-- Tạo bảng NHANVIEN 
CREATE TABLE NHANVIEN (
    MANV VARCHAR(10) PRIMARY KEY NOT NULL, 
    TENNV NVARCHAR(255) NOT NULL,  
    NGAYSINH DATE NOT NULL, 
    DIACHI NVARCHAR(255) NOT NULL ,  
    SDT VARCHAR(15) UNIQUE,  
    CCCD VARCHAR(50) UNIQUE, 
    CHUCVU NVARCHAR(50) NOT NULL, 
    CONSTRAINT CK_SDT CHECK (SDT LIKE '0%' AND LEN(SDT) BETWEEN 10 AND 12)  
);

-- Tạo bảng TAIKHOAN 
CREATE TABLE TAIKHOAN (
    MANV VARCHAR(10) NOT NULL PRIMARY KEY,
    MATKHAU VARCHAR(225) NOT NULL,
	FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV)
);

-- Tạo bảng CALAM
CREATE TABLE CALAM (
    MACA VARCHAR(10) NOT NULL PRIMARY KEY ,  
    NGAY_LV DATE NOT NULL,  
    BUOI_LAM NVARCHAR(10) NOT NULL,  
    GIO_BATDAU TIME NOT NULL,  
    GIO_KETTHUC TIME NOT NULL, 
);

-- Tạo bảng LICHLAM 
CREATE TABLE LICHLAM (
    MANV VARCHAR(10) NOT NULL,  
    MACA VARCHAR(10) NOT NULL,  
    PRIMARY KEY (MANV, MACA),  
    FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV),  
    FOREIGN KEY (MACA) REFERENCES CALAM(MACA),
);



-- Tạo bảng BANGLUONG 
CREATE TABLE BANGLUONG (
    MANV VARCHAR (10) NOT NULL, 
    BANGLUONG_DATE DATE NOT NULL,  
    LUONGCOBAN DECIMAL(18, 2) NOT NULL,  
    TONGLUONG DECIMAL(18, 2) NOT NULL, 
    PRIMARY KEY (MANV, BANGLUONG_DATE),  
    FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV),  
    CONSTRAINT CK_LUONG CHECK (LUONGCOBAN >= 0 AND TONGLUONG >= 0)  
);





-- Tạo bảng CHAMCONG 
CREATE TABLE CHAMCONG (
    MANV VARCHAR (10) NOT NULL,  
    CHAMCONG_DATE DATE NOT NULL,  
    TONGCACHAMCONG INT NOT NULL, 
    THUONG DECIMAL(18, 2) NULL, 
    PHAT DECIMAL(18, 2) NULL,  
    PRIMARY KEY (MANV, CHAMCONG_DATE),  
    FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV),  
    CONSTRAINT CK_CHAMCONG CHECK (TONGCACHAMCONG >= 0 AND THUONG >= 0 AND PHAT <= 0)  
);



-- Thay đổi các cột trong bảng NHANVIEN thành NULL
ALTER TABLE NHANVIEN ALTER COLUMN TENNV NVARCHAR(255) NULL
ALTER TABLE NHANVIEN ALTER COLUMN NGAYSINH DATE NULL;
ALTER TABLE NHANVIEN ALTER COLUMN DIACHI NVARCHAR(255) NULL
ALTER TABLE NHANVIEN ALTER COLUMN SDT VARCHAR(15) NULL;
ALTER TABLE NHANVIEN ALTER COLUMN CCCD VARCHAR(50) NULL;
ALTER TABLE NHANVIEN ALTER COLUMN CHUCVU NVARCHAR(50) NULL

-- Thay đổi các cột trong bảng TAIKHOAN thành NULL
ALTER TABLE TAIKHOAN ALTER COLUMN MATKHAU VARCHAR(225) NULL

-- Thay đổi các cột trong bảng CALAM thành NULL
ALTER TABLE CALAM ALTER COLUMN BUOI_LAM NVARCHAR(10) NULL
-- Thay đổi các cột trong bảng BANGLUONG thành NULL
ALTER TABLE BANGLUONG ALTER COLUMN TONGLUONG DECIMAL(18,2) NULL;
ALTER TABLE BANGLUONG ALTER COLUMN LUONGCOBAN DECIMAL(18,2) NULL;

--Them cột TRANGTHAI vao bảng LICHLAM 
ALTER TABLE LICHLAM
ADD TRANGTHAI INT NULL
CONSTRAINT CK_TRANGTHAI CHECK (TRANGTHAI IN (0, 1, 2))
--Them cột SOGIOLAMVIEC vào bảng CALAM 
ALTER TABLE CALAM
ADD SOGIOLAMVIEC INT NULL 
--Đổi column TONGCACHAMCONG thành TONGSOGIOLAM 
ALTER TABLE CHAMCONG 
DROP CONSTRAINT CK_CHAMCONG;

ALTER TABLE CHAMCONG
DROP COLUMN TONGCACHAMCONG;

ALTER TABLE CHAMCONG
ADD TONGSOGIOLAM INT NULL;

ALTER TABLE CHAMCONG
ADD CONSTRAINT CK_TONGSOGIOLAM CHECK (TONGSOGIOLAM >= 0 AND THUONG >= 0 AND PHAT <= 0)



Select * From BANGLUONG
Select * From CHAMCONG
Select * From TAIKHOAN
Select * From CALAM
Select * From NHANVIEN
Select * From LICHLAM


ALTER TABLE TAIKHOAN
DROP COLUMN ENCRYPTED_MATKHAU;

ALTER TABLE NHANVIEN
DROP COLUMN ENCRYPTED_SDT;

ALTER TABLE NHANVIEN
DROP COLUMN ENCRYPTED_CCCD;

DISABLE TRIGGER trg_RandomPassword ON TAIKHOAN;

DISABLE TRIGGER tr_capnhatdl ON NHANVIEN;

SELECT * 
FROM sys.triggers
WHERE parent_id = OBJECT_ID('TAIKHOAN');

SELECT * 
FROM sys.triggers
WHERE parent_id = OBJECT_ID('NHANVIEN');


ALTER TABLE CHAMCONG NOCHECK CONSTRAINT CK_TONGSOGIOLAM;
-- Thực hiện cập nhật
-- Bật lại ràng buộc
ALTER TABLE CHAMCONG CHECK CONSTRAINT CK_TONGSOGIOLAM;


DISABLE TRIGGER ALL ON LICHLAM;
-- Thực hiện cập nhật
ENABLE TRIGGER ALL ON LICHLAM;





SELECT name 
FROM sys.foreign_keys 
WHERE parent_object_id = OBJECT_ID('LICHLAM');

SELECT name 
FROM sys.foreign_keys 
WHERE parent_object_id = OBJECT_ID('CHAMCONG');

ALTER TABLE LICHLAM NOCHECK CONSTRAINT ALL;
ALTER TABLE LICHLAM CHECK CONSTRAINT FK_LICHLAM_MACA;

ALTER TABLE CHAMCONG NOCHECK CONSTRAINT FK__CHAMCONG__MANV__48CFD27E;

ALTER TABLE CHAMCONG NOCHECK CONSTRAINT FK__CHAMCONG__MANV__48CFD27E;

SELECT name, OBJECT_DEFINITION(object_id) AS TriggerDefinition
FROM sys.triggers
WHERE parent_id = OBJECT_ID('CHAMCONG');


DISABLE TRIGGER TRG_TINHTONGLUONG1 ON CHAMCONG;
DISABLE TRIGGER TR_TinhThuongPhat9 ON CHAMCONG;
